type Note {
  id: ID!
  title: String!
}

type Query {
  notes: [Note!]
}

type Mutation {
  createNote(title: String!): Note!
  deleteNote(id: String!): Note!
  updateNote(id: String!, title: String!): Note!
}
